FROM openjdk:18-slim

WORKDIR /app
COPY libs/bcprov-jdk18on-1.78.1.jar libs/
COPY src/DSTP/ src/DSTP/
COPY src/TestMulticast/ src/TestMulticast/
COPY src/cryptoconfig.txt src/

WORKDIR /app/src
RUN javac -cp .:../libs/bcprov-jdk18on-1.78.1.jar DSTP/*.java TestMulticast/*.java

ENTRYPOINT ["java", "-cp", ".:../libs/bcprov-jdk18on-1.78.1.jar", "TestMulticast.MulticastReceiver"]
CMD ["239.0.0.1", "5000"]
