services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    network_mode: "host"
    depends_on:
      - server
    command: ["user1@email.com", "password1", "localhost", "3333", "cars.dat", "5000", "9000"]

  server:
    build:
      context: .
      dockerfile: Dockerfile.streamServer
    network_mode: "host"
