FROM openjdk:18-slim

WORKDIR /app
COPY libs/bcprov-jdk18on-1.78.1.jar libs/
COPY src/DSTP/ src/DSTP/
COPY src/SHP/ src/SHP/
COPY src/StreamingService/ src/StreamingService/
COPY src/ClientECCKeyPair.sec src/
COPY src/ServerECCPubKey.sec src/

WORKDIR /app/src
RUN javac -cp .:../libs/bcprov-jdk18on-1.78.1.jar DSTP/*.java SHP/*.java StreamingService/**/*.java

ENTRYPOINT ["java", "-cp", ".:../libs/bcprov-jdk18on-1.78.1.jar", "StreamingService.hjUDPproxy.hjUDPproxy"]
