FROM openjdk:18-slim

WORKDIR /app
COPY libs/bcprov-jdk18on-1.78.1.jar libs/
COPY src/DSTP/ src/DSTP/
COPY src/SHP/ src/SHP/
COPY src/StreamingService/ src/StreamingService/
COPY src/ciphersuite.conf src/
COPY src/userdatabase.txt src/
COPY src/ServerECCKeyPair.sec src/

WORKDIR /app/src
RUN javac -cp .:../libs/bcprov-jdk18on-1.78.1.jar DSTP/*.java StreamingService/**/*.java

ENTRYPOINT ["java", "-cp", ".:../libs/bcprov-jdk18on-1.78.1.jar", "StreamingService.hjStreamServer.hjStreamServer"]
