FROM openjdk:18-slim

WORKDIR /app
COPY TFTPClient/libs/bcprov-jdk18on-1.78.1.jar libs/
COPY TFTPClient/src/ src/

WORKDIR /app/src
RUN find . -name '*.class' -delete && javac -cp .:../libs/bcprov-jdk18on-1.78.1.jar DSTP/*.java SHP/*.java *.java

ENTRYPOINT ["java", "-cp", ".:../libs/bcprov-jdk18on-1.78.1.jar", "TFTPClient"]
